Use the JIRA REST Api to transfer tickets into Thunderdome
StevenWeathers/thunderdome-planning-poker pull request #124
Opened 2020-10-30 08:35 UTC by tnonnenm

Jira has a great REST API that allows the search for tickets (Stories, Bugs, ...) based on the JQL.
This PR adds the ability to "ask" Jira directly for tickets using the same JQL one would use to export tickets as XML.

By default the feature is disabled since it requires further configuration:
* pre-define the correct server URL (optional, if not set the user must change the dummy on the dialogue)
* Jira limits the amount of tickets in the REST response results to 50 - this can be set to a different value (default is 30)
* The "acceptance criteria" is a custom field in Jira (added by an extension) and needs to be configured here (e.g. as customfield_15023) - otherwise no acceptance criteria will show up

Advantage: I had several issues with the XML export since Jira does not generate error free XML in our cases - there was always something to fix before importing. The REST interface is pretty fast and requests only the few attributes that are required to setup a plan

2020-10-30 12:37 UTC, eivindt commented
As someone not using Jira, I'm not too thrilled about this pull request.  The number of changes are quite high and Jira specific.  How would I go about adding support for _my_ issue tracker?  It would quickly end up messy.

I'd prefer a solution that did it the other way around, add a REST interface to Thunderdome. 

Then, the jira support could either be added as a Jira plugin, or as a separate script/command for fetching issues using the Jira REST api and converting them into the Thunderdome REST api.

Then I could easily add support for my own issue tracker without patching up the core Thunderdome code.

2020-10-30 12:44 UTC, StevenWeathers commented
> As someone not using Jira, I'm not too thrilled about this pull request. The number of changes are quite high and Jira specific. How would I go about adding support for _my_ issue tracker? It would quickly end up messy.
> 
> I'd prefer a solution that did it the other way around, add a REST interface to Thunderdome.
> 
> Then, the jira support could either be added as a Jira plugin, or as a separate script/command for fetching issues using the Jira REST api and converting them into the Thunderdome REST api.
> 
> Then I could easily add support for my own issue tracker without patching up the core Thunderdome code.

An external facing API is something I'm planning on doing very soon, though Jira is by far the most popular especially in enterprise, I will need to think about this one in particular and try it out locally to determine if I want to bring it in.

2020-10-30 13:07 UTC, StevenWeathers requested changes
If you could make the mentioned changes regarding API authentication and the existing jira config value then I will test this locally and consider merging it.

2020-10-30 13:07 UTC, StevenWeathers commented on config.go
> +	viper.BindEnv("config.allow_jira_import_xml", "CONFIG_ALLOW_JIRA_IMPORT_XML")
we can't go about changing existing config values, this would be a breaking change.

2020-10-30 13:07 UTC, StevenWeathers commented on frontend/src/components/JiraImportServerData.svelte
> +            password,
"Support for passwords in REST API basic authentication is deprecated and will be removed in the future. While the Jira REST API currently accepts your Atlassian account password in basic auth requests, we strongly recommend that you use API tokens instead. We expect that support for passwords will be deprecated in the future and advise that all new integrations be created with API tokens."

Source: https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/

Therefore, the best route would be to have the user enter a Jira API Token and store it in the users profile so they don't have to keep re-entering it.

2020-10-30 13:07 UTC, StevenWeathers commented on frontend/src/components/JiraImportServerData.svelte
> +                                    bind:value="{apiEndpoint}"
I assume this is here to support non corporate (single jira endpoint) usecase, such as Thunderdome.dev where a user could provide any jira url that is accessible with the given API token and Thunderdome could reach out to it.

2020-10-30 13:07 UTC, StevenWeathers commented on frontend/src/components/JiraImportServerData.svelte
> +                            <input
I think from a UX perspective the user should be able to see the result of the JQL and select only the stories they actually want.  Also I'm not too versed in JQL so I assume most end users wont be as well, will need to consider another option such as fetching stories from a specific epic or backlog somehow.

2020-10-30 14:58 UTC, tnonnenm commented on frontend/src/components/JiraImportServerData.svelte
> +            password,
I know and this was also my first thought. However, our company Jira server does not allow me to create an API access token ... so the only way accessing the server is currently the basic auth.

I'll contact the server's administrator and ask... so I can test this...

2020-10-30 15:00 UTC, tnonnenm commented on frontend/src/components/JiraImportServerData.svelte
> +                                    bind:value="{apiEndpoint}"
Exactly ... the config value is for those who have the poker running on an internal server.

I could remove the default from config and show this field only on UI, if there is nothing set in the configuration.

2020-10-30 15:03 UTC, StevenWeathers commented on frontend/src/components/JiraImportServerData.svelte
> +            password,
Perhaps an option to decide what method of auth is used

2020-10-30 15:04 UTC, StevenWeathers commented on frontend/src/components/JiraImportServerData.svelte
> +                                    bind:value="{apiEndpoint}"
I would say if the config value is set then don't show the field if not show the field that way internal use can be controlled.

2020-11-02 00:44 UTC, vasileknik76 commented on config.go
> +	viper.BindEnv("config.allow_jira_import_xml", "CONFIG_ALLOW_JIRA_IMPORT_XML")
Viper allows add aliases. It may help with backward compability. 
https://github.com/spf13/viper#registering-and-using-aliases

2020-11-03 05:43 UTC, tnonnenm commented on frontend/src/components/JiraImportServerData.svelte
> +            password,
API Token is supported by Jira Cloud, not by Jira Server. I will use my Atlassian account to test the API Token for cloud and the company's server for basic auth.

2020-11-03 15:16 UTC, StevenWeathers commented on frontend/src/components/JiraImportServerData.svelte
> +            password,
> API Token is supported by Jira Cloud, not by Jira Server. I will use my Atlassian account to test the API Token for cloud and the company's server for basic auth.

Sounds good

2020-11-08 20:45 UTC, tnonnenm commented
Took a while. 
Tested with Jira Cloud: for token method the email is used as username and the token as password with basic auth.

2020-11-09 13:50 UTC, merged

2020-11-09 13:51 UTC, StevenWeathers commented
Thanks I've merged to a new branch so I may spend some time looking at the integration as a whole.