Combine team battles
StevenWeathers/thunderdome-planning-poker pull request #504
Opened 2024-03-22 19:06 UTC by budokaiman

Include team battles in "my battles/retros/storyboards". I opted to include team battles in the existing list as I found it the easiest to navigate as well as making logical sense (especially if using retros/storyboards). If a user is added to an existing team, they will be able to see past battles and retros for the team, but they will still be listed under current ones. There are no duplicates or need for condensing results. Team items are indicated by the team name next to the item name.

I had also considered the following before settling on the combined view
* showing team battles underneath my battles - this make the landing page look bloated and there were frequently duplicated results. It also meant having to look around more when wishing to join a new team battle
* showing team battles between my battles and create - this made the landing page very squished, though easier to navigate
* automatically adding team members to battles on battle creation - this has the downside of not really seeing who is participating, and historical battles still need to be found through individual teams

![image](https://github.com/StevenWeathers/thunderdome-planning-poker/assets/2196125/5e11e2c5-2a35-43aa-a9ab-c2084e885762)

Addresses Issue #168

2024-03-22 21:57 UTC, scottux requested changes
Just two comment updates that I see. I have made suggestions.

2024-03-22 21:57 UTC, scottux commented on ui/src/i18n/i18n-types.ts
> +   * M​y​ ​R​e​t​r​o​s
```suggestion
   * T​eam​ ​R​e​t​r​o​s
```

2024-03-22 21:57 UTC, scottux commented on ui/src/i18n/i18n-types.ts
> +   * M​y​ ​S​t​o​r​y​b​o​a​r​d​s
```suggestion
   * Team​ ​S​t​o​r​y​b​o​a​r​d​s
```

2024-03-22 22:00 UTC, scottux commented
I question the naming of `ownerNameField` and `showOwnerName`. The default seems to be showing the team name, but functionally it could be any extra field that is defined.

Maybe it should be more explicit `teamNameField` and `showTeamName` instead.

2024-03-22 22:04 UTC, budokaiman commented
> I question the naming of `ownerNameField` and `showOwnerName`. The default seems to be showing the team name, but functionally it could be any extra field that is defined.
> 
> Maybe it should be more explicit `teamNameField` and `showTeamName` instead.

I went back and forth on this, and decided to stick with "owner name field" in case there was ever a time that an owning user should be shown over the owning team. This would reduce the need for extra variables or a subsequent rename. Let me know if you still disagree, I can change the naming

2024-03-22 23:40 UTC, StevenWeathers commented on ui/src/i18n/en/index.ts
I see new additions to the locale files however these new keys are not in use in this PR, either remove them or use them.

2024-03-22 23:45 UTC, StevenWeathers commented
I greatly appreciate this PR and will be happy to accept it once the locale file issue is sorted out.

2024-03-23 11:06 UTC, budokaiman commented on ui/src/i18n/en/index.ts
This was definitely an artefact of when I was trying out the double columns. Removed.

2024-03-23 11:06 UTC, budokaiman commented
> I greatly appreciate this PR and will be happy to accept it once the locale file issue is sorted out.

Cheers, I greatly appreciate the software you've built, so happy to contribute where able.

2024-03-24 12:52 UTC, scottux approved these changes

2024-03-24 13:44 UTC, StevenWeathers approved these changes

2024-03-24 13:44 UTC, merged